### ISSUE TITLE
inference_partition.py encountering runtime errors

### ISSUE THREAD

**Issue by JeremyIV** [huai-chang/DiffEIC#10]
Hi, thanks for providing your code and weights for this project!

I an trying to run inference with your pretrained models as instructed in the readme. I am running this command:

```
python3 inference_partition.py \
--ckpt_sd ./weight/v2-1_512-ema-pruned.ckpt \
--ckpt_lc ./weight/1_2_1/lc.ckpt \
--config configs/model/diffeic.yaml \
--input /scratch/vonder2/kodak-dataset/ \
--output results/0.12bpp \
--steps 50 \
--device cuda 
```

However, I've encountered a few issues now which make me less-than-confident that it'll be easy to get inference running as intended.

First, the instructions have the argument `--devide` instead of --device`. Second, there are at least a couple issues with line 116 of inference_partition.py

```
load_state_dict(model, ckpt = {'state_dict': ckpt_sd.update(ckpt_lc)}, strict=False)
```

1) This `load_state_dict` function has no argument `ckpt`. 
2) `ckpt_sd.update(ckpt_lc)` updates the state dict in place and returns `None`, so it's not appropriate to pass this in as an argument. 

I could keep correcting these errors, but I get the feeling I am working with untested code here. Is there an older checkpoint in the repository that you recommend I roll back to or something?

**Comment by huai-chang** [comment]
Hi, thank you for bringing these issues to our attention!

The code you’re working with is indeed a checked version, but `inference_partition.py` was added later, and it wasn’t thoroughly tested at that time. I really appreciate you pointing out these errors. I’ve corrected them now to ensure smooth execution. I’ll conduct a comprehensive review of all code once again to prevent similar issues. Thank you again for helping us improve!

**Comment by JeremyIV** [comment]
oh, I guess that was all it took to get it working! Thanks for the quick response!
