### ISSUE TITLE
论文细节

### ISSUE THREAD

**Issue by Accept111** [huai-chang/DiffEIC#3]
作者你好。
1、就是关于论文，在图像重建模块，这个Zt是潜在噪声，是从哪来的，具体在代码哪块体现出来的。
2、Zc是内容变量会注入到去噪过程中，就是我如果要传输压缩的内容，具体是Zc还是Zt是压缩后的内容呢。

**Comment by huai-chang** [comment]
问题1：就是关于论文，在图像重建模块，这个 $Z_t$ 是潜在噪声，是从哪来的，具体在代码哪块体现出来的。

在训练过程中， $Z_t$ 是通过对原始图像的潜在特征 $Z_0$ 进行加噪操作得到的: $Z_t = \sqrt{\bar{\alpha_t}}Z_{0} + \sqrt{1-\bar{\alpha_t}}\epsilon ,\  t=1,2,\cdots,T$ ，具体可见论文的 `Section III-B 1)Stable Diffusion`， 相关代码在`model/diffeic.py`的第734行。在推理阶段，我们直接使用完全噪声作为 $Z_T$ ，相关代码在`inference_partition.py`的第60行。

---
问题2： $Z_c$ 是内容变量会注入到去噪过程中，就是我如果要传输压缩的内容，具体是 $Z_c$ 还是 $Z_t$ 是压缩后的内容呢。

$Z_c$ 是压缩后内容，而 $Z_t$ 是扩散过程的中间变量。在我们的方法中， $Z_c$ 作为生成过程的外部引导是固定不变的，而 $Z_t$ 会随着去噪过程的进行发生改变。 （PS 不知道我有没有正确理解你的问题，但传输的话一般是传输中间的码流而非特征？）

**Comment by Accept111** [comment]
对，传输熵编码后的码流。Zc是压缩后的内容，我如果要进行存储或者传输怎么办？
还有就是你做的应该是极低比特的压缩，我想问一下压缩率是在哪块体现的，就是我想进一步提高压缩率应该怎么办？

**Comment by huai-chang** [comment]
中间码流会统一保存在一个data文件夹下，你需要传输的就是这个文件，压缩率就是使用这个文件的大小除以原图像素数
<img width="352" alt="image" src="https://github.com/user-attachments/assets/1faa0ed6-64e9-432d-baa2-a99c0a29f5cf">

**Comment by Accept111** [comment]
在代码和模型设计中是在哪体现的呢
