### ISSUE TITLE
训练过程梯度消失

### ISSUE THREAD

**Issue by Accept111** [huai-chang/DiffEIC#6]
作者你好！
我跑了一下你的训练代码，但是我在训练到第四个epoch的时候出现了梯度消失的情况。
请问是什么问题呢？
感谢作者回答。
![image](https://github.com/user-attachments/assets/2596a297-8487-45ab-99d3-cf82f7c5e68d)

**Comment by huai-chang** [comment]
我在训练的时候也遇到了这个问题。但我并没有找到具体的原因，这个问题似乎是随机出现的。你可以接着之前保存的正常的checkpoint继续训练，这在我的训练过程中是起作用的。

**Comment by Accept111** [comment]
我还想问一下有损失的趋势图嘛，我大概看了一下，损失由上千到个位数，又会变成好几十。

**Comment by huai-chang** [comment]
你是指哪个损失呢？

**Comment by Accept111** [comment]
训练过程中打印的loss和aux_loss

**Comment by huai-chang** [comment]
我没有找到当时保存的tensorboard文件，但aux_loss我记得大致是这么个趋势。你说的情况应该是正常的。
<img width="680" alt="image" src="https://github.com/user-attachments/assets/9711689f-dd31-4682-84f6-f3a26855c5e5">

**Comment by Accept111** [comment]
好的，我懂了，谢谢作者
